const data = {
  products: [
    // Object=>{}
    {
      _id: "1",
      name: "Mens Shirt",
      slug: "shirt",
      category: "Shirt",
      image: "/images/model3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "2",
      name: "kids Shirt",
      slug: "kids-shirt",
      category: "Shirt",
      image: "/images/model4.jpg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 3,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "3",
      name: "White Shirt",
      slug: "white-shirt",
      category: "Shirt",
      image: "/images/model5.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "4",
      name: "Mens Shoes",
      slug: "nike-shoes",
      category: "Shoes",
      image: "/images/shoes7.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "5",
      name: "Mens Shoes",
      slug: "nike-mens-shoes",
      category: "Shoes",
      image: "/images/shoes10.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "6",
      name: "Mens Jacket",
      slug: "nike-jacket",
      category: "Jacket",
      image: "/images/jacket.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "7",
      name: "Mens Hoodie",
      slug: "hoodie",
      category: "Hoodie",
      image: "/images/hoodie.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "8",
      name: "Mens Jacket",
      slug: "nike-mens-jacket",
      category: "Shoes",
      image: "/images/jacket1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};
export default data;
