const data = {
  products: [
    // Object=>{}
    {
      name: "Nike Shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/model3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Denim Pant",
      slug: "denim-pant",
      category: "Pant",
      image: "/images/model4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Skirt",
      slug: "skirt-girls",
      category: "Skirt",
      image: "/images/model5.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Shoes",
      slug: "nike-shoes",
      category: "Shoes",
      image: "/images/model3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};
export default data;
