const data = {
  products: [
    // Object=>{}
    {
      name: "Nike Mens Shirt",
      slug: "nike-shirt",
      category: "Shirt",
      image: "/images/model3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike kids Shirt",
      slug: "kids-shirt",
      category: "Shirt",
      image: "/images/model4.jpg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 3,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Summ Shirt",
      slug: "summer-shirt",
      category: "Shirt",
      image: "/images/model5.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Mens Shoes",
      slug: "nike-shoes",
      category: "Shoes",
      image: "/images/shoes7.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};
export default data;
